### ISSUE TITLE
Add postgres-operator to "DI2-ME" software factory

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf-package-software-factory#10]
**Outcome:**
We want to add a Kubernetes operator for Postgres to the "[DI2-ME](defenseunicorns/zarf-package-software-factory#22)" software factory Zarf package, so that we can use it to manage postgres databases that the individual services need in a way that is performant, stable, and able to be backed up

**Notes:**
* A few months ago we created a [Zarf example](https://github.com/defenseunicorns/zarf/tree/master/examples/postgres-operator) that uses Zalando's Postgres Operator. It looks to work pretty well, and that operator is already present in [Iron Bank](https://registry1.dso.mil/harbor/projects/3/repositories/opensource%2Fzalando%2Fpostgres-operator) so that's a plus too, but we aren't married to any specific tools
* We ARE married to wanting to use the Kubernetes Operator pattern, and one of the Postgres operators that are available, with a strong preference for something that is free and open source.

**Acceptance Criteria:**
1. The operator deploys as part of the Zarf package, but doesn't need to deploy any databases yet
2. Must work on Big Bang without sacrificing the existing security stance (the existing Zarf example does not use Big Bang so this will be new trailblazing)

**Future backlog items:**
- [ ] Update all services that need a postgres database to use one provided by the postgres operator
- [ ] Configure backup

**Comment by david--wright** [comment]
If that is it for comments I am more than willing to do that.

**Comment by RothAndrew** [comment]
K. I'm gonna add you as the assignee and move it to "Doing Now" in the board. Please let us know if you need/want any support or pairing.

**Comment by david--wright** [comment]
After reviewing the different options for this it looks like the best path is going to be to do this in three stages. 
1) Integrate the existing postgres-operator example with the software factory
2) Change the ingress to use istio / integrate with the bigbang monitoring stack
3) Change the configuration to use the bigbang provided images and charts. The example currently uses the upstream ones.

I should have a draft PR up later today for step 1 - I'll update here when that is up.

**Comment by david--wright** [comment]
#42 Implements step 1. After some discussion it sounds like we dont want to do step 2 since outside access to the database is not desired.
