### ISSUE TITLE
Backup & Restore procedures for a "self sufficient" cluster

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf-package-software-factory#121]
As a user of a "self sufficient" ZPSF I want the ability to restore my software factory from a backup so that I can recover data if it is lost

AC:
1. I'm able to follow a documented procedure to restore my software factory from a backup with the outcome being a live cluster that is in the same state as it was when the backup was taken

Notes:
- "Self sufficient" means using MinIO and Postgres Operator inside the cluster, and not using any external services like S3 or RDS
- The idea right now is to use Velero to backup/restore the whole cluster, from one or more artifacts that are stored outside of the cluster.

**Comment by RothAndrew** [comment]
#377 adds Velero and Restic to the cluster, here's the current plan for a complete disaster recovery scenario assuming a "self contained" cluster (i.e. not using external services like RDS or S3)

Before the "disaster"
1. Create a set of Velero backups that will get placed in the cluster's MinIO, that each backs up a single namespace
    - `gitlab`
    - `jira`
    - `confluence`
    - `jenkins`
    - `artifactory`
    - `minio`
1. User is responsible for migrating the backups to somewhere safe that is outside of the cluster's "blast radius". Intent is to create an automated procedure/script/program that handles this step that can be provided to the user.

After the "disaster"
1. Create a Zarf "restore package" that creates:
    1. A new namespace (`tmp-backupstoragelocation`?)
    1. a deployment of MinIO to the new namespace
    1. A pod with the MinIO CLI installed, with the backup artifact(s) injected into its filesystem, that pushes the artifact(s) into MinIO as a job
    1. A new `backupstoragelocation` and secret to the `velero` namespace so that a restore can be done from the new location
1. Deploy the software factory fully, so that it is up and working, but empty of all user-generated data
1. Run `flux suspend kustomization bigbang && flux suspend kustomization softwarefactoryaddons`
1. Delete the HelmReleases for GitLab, Jira, Confluence, Jenkins, Artifactory, and MinIO, resulting in Flux deleting those services from the cluster
2. Deploy the Zarf "restore package"
3. Run a velero restore for each service to be restored, starting with MinIO (since other services depend on it)
4. Run `flux resume kustomization bigbang && flux resume kustomization softwarefactoryaddons`

Development Tasks:
* Create the zarf configuration for the new "restore package"
* Add this procedure to the automated test suite
* (separate issue) Create automation script/program/something that makes this procedure "push-button"

**Comment by RothAndrew** [comment]
This issue is starting to feel like a never-ending rabbit hole. I have the "disaster recovery" zarf package mostly done, and it deploys fine. But now I'm realizing that Velero needs to take backups to somewhere that it can use just for its own use.

If Velero is using the main MinIO and I run `velero backup create minio --include-namespaces minio` it is not happy since it is backing up to the same place that it is backing up, creating somewhat of a circular dependency. The backup was ultimately successful but it threw a warning and I'm concerned about how it may behave if backups are not cleared out of minio in a timely manner. Each subsequent backup will also contain all of the backups that came before it, causing each backup to grow in size exponentially.

Now I'm thinking the right way to go is to have DI2-ME come with 2 instance of MinIO. One for Velero's exclusive use, and one for everything else that needs buckets

**Comment by RothAndrew** [comment]
We weren't able to get Velero to cleanly take a backup of GitLab without taking down GitLab so we are instead using a combination of Velero and GitLab's own backup utility. GitLab's backup utility will take the backup of the database, LFS, artifacts, repos, registry, etc, and Velero will back up the secrets in the Gitlab namespace which are needed to do a restore since they have the database encryption keys.

The next step is to come up with some kind of utility that will make it easy to automatically pull both the gitlab backup and the velero backup out of the cluster and to somewhere safe, with the ability to reverse the process and kick off a restore when needed.

**Comment by RothAndrew** [comment]
Rough design for the utility mentioned above:

* New folder "backup-and-restore"
* New zarf package definition in backup-and-restore folder called "di2me-backup-and-restore"
* Zarf package contains a component for each backup-able service, starting with GitLab

```
components:
  - name: gitlab
     scripts:
       prepare:
         - Use kubectl to pull the gitlab backup and the velero back of gitlab's secrets into the local filesystem
         - Make 100% sure that the backups live locally, then delete the backups in the cluster to save storage space
       after:
         - Push the backups into the cluster
         - Trigger a restore using kubectl exec
     files:
        - the backup files
```

@blancharda @jeff-mccoy @Racer159 @YrrepNoj thoughts?

**Comment by blancharda** [comment]
Is there an advantage to writing it as a Zarf package as opposed to just a simple script (or scripts)?

**Comment by RothAndrew** [comment]
Advantages that I'm seeing:

1. The user is already used to using Zarf, and this would be a familiar pattern for them
2. The logic and the backup artifacts are contained in the same file

Will look at making triggering the restore something optional/opt-in
