### ISSUE TITLE
Ensure coredns modification persistence

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/zarf-package-software-factory#195]
This may be a non-issue related to my test environment - but it seems worth mentioning...

On restarting my test environment VM (or at some other point), it appears that K3S (my cluster distro) overwrote the changes to the coredns configmap.

Since this change is really only required to support local development and ephemeral tests, neither of which should require environment restarts, I'm not sure this is worth tracking down.. but we may be able to mitigate it by removing the "ownership" annotations.

_Originally posted by @blancharda in https://github.com/defenseunicorns/zarf-package-software-factory/issues/130#issuecomment-1156584647_

**Comment by RothAndrew** [comment]
I agree that this is likely a non-issue since bigbang.dev is only intended to be used in local dev or automated tests.

**Comment by RothAndrew** [comment]
@blancharda do you foresee that this will be an issue for you? It isn't for me, but I always run `zarf destroy --confirm` before I shut down my machine.
