### ISSUE TITLE
ADR on SSO Provider

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf-package-software-factory#23]
Outcome:
We want an Architecture Decision Record (ADR) on which tool is being used as the SSO provider for the "DI2-ME" software factory package, so that we can use it as a baseline when completing SSO-related work across the codebase.

**Comment by anoncam** [comment]
https://github.com/ory/hydra

Might be an interesting option

**Comment by anoncam** [comment]
ory.sh

**Comment by RothAndrew** [comment]
@anoncam the options in front of us right now are either using Keycloak that comes with Big Bang Umbrella, or using GitLab (also from Big Bang Umbrella) as the SSO provider. Not tracking any other alternatives at the moment, though open to suggestions.

**Comment by RothAndrew** [comment]
Currently reading https://github.com/joelparkerhenderson/architecture-decision-record as a guide. 6.3k stars, lots of examples, well documented. Will write out a high-level plan for how I want to tackle this after.

**Comment by RothAndrew** [comment]
I'm seeing quite a few recommendations on using the tool https://github.com/npryce/adr-tools. It looks like it would make it simpler to establish a standard format for the documents, along with also automatically updating previous documents when they are amended or superseded by later decisions.

https://github.com/joelparkerhenderson/architecture-decision-record/blob/main/templates/decision-record-template-by-michael-nygard/index.md

**Comment by anoncam** [comment]
> I'm seeing quite a few recommendations on using the tool https://github.com/npryce/adr-tools. It looks like it would make it simpler to establish a standard format for the documents, along with also automatically updating previous documents when they are amended or superseded by later decisions.
> 
> https://github.com/joelparkerhenderson/architecture-decision-record/blob/main/templates/decision-record-template-by-michael-nygard/index.md

cool -- ya i threw that out b/c sso from BB are shitty options for something that is foundational.  cool tool.  does it seem overkill to have a ADR for ADRs?

**Comment by anoncam** [comment]
You are only slowing yourself down to a good solution by putting a bunch of bullshit process in front of stuff...code speaks for itself...those templates do as well as I suppose 🤣

**Comment by RothAndrew** [comment]
@anoncam I'm open to suggestions on how you would do it. My goal is to document a norm for this repository on how we do ADRs so that a junior engineer or someone new to the team, or a 3rd party contributor, has a place to go to understand why we do them and what expectations we have for them.

In my research, I happened across several projects that used their first ADR to document their decision to do ADRs, and it seemed a logical approach. You are not the only person that it has been deeply unpopular with. I think a README.md that talks about our strategy for documenting architecturally significant decisions would be just as suitable, and if it doesn't cause people to throw up in their mouth because of its appearance, then that is better too.

**Comment by anoncam** [comment]
@RothAndrew, I think that proper `README` docs are pretty sufficient and then can contribute more towards the documentation of the product for the end-user.  

A process that project maintainers abide by when considering feature requests/PRs can be documented in a single file `CONTRIBUTING` and even an extra `GUIDELINES.`   

This leverages the inherent audibility of git while keeping it simple.  You can set up an oversight committee if you want project governance. Still, in my experience, the ADR process has been nothing but frustrating for me and has led to me losing motivation to pursue ideas.  The risk of stifling creativity is exponentially more critical to prevent versus a lot of documentation around every architectural decision.
