### ISSUE TITLE
Update compatibility to Zarf v0.15.0

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf-package-software-factory#24]
Outcome:
We want to update the package to be compatible with the latest version of Zarf, which is currently v0.15.0

**Comment by RothAndrew** [comment]
Working on this now. I don't expect there to be any significant roadblocks so should be able to get it out in the next day or two.

**Comment by RothAndrew** [comment]
@jeff-mccoy have you had a chance to try this yet?

**Comment by jeff-mccoy** [comment]
Arg sorry I will tonight if that's okay I forgot #fireJeff

**Comment by RothAndrew** [comment]
![you_are_terminated](https://media.giphy.com/media/qHnkJbu23etNiTu7Wa/giphy.gif)
