### ISSUE TITLE
Upgrade Big Bang to resolve GitLab CVE

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf-package-software-factory#256]
https://about.gitlab.com/releases/2022/06/30/critical-security-release-gitlab-15-1-1-released/

As soon as GitLab v15.1.1 is available through Big Bang, we should update Big Bang to use it.

**Comment by audreytoskin** [comment]
There were also vulnerabilities patched in GitLab 14.x, if we don't necessarily want to jump to GitLab 15 yet.
https://about.gitlab.com/releases/2022/02/03/security-release-gitlab-14-7-1-released/

**Comment by RothAndrew** [comment]
The version configured in main right now is 15.0.1, which is the latest version that Big Bang offers.

**Comment by RothAndrew** [comment]
Upgrading Big Bang to v1.39.0 will resolve this, as it has now been released and it runs GitLab v15.1.2
