### ISSUE TITLE
Ignore annotations created on PostgreSQL databases when deploying to EKS

### ISSUE THREAD

**Issue by mikevanhemert** [defenseunicorns/zarf-package-software-factory#317]
When the software factory is deployed into EKS, the PostgreSQL operator will cycle databases every 30 minutes because EKS applies an annotation to the StatefulSets. See [Zalando docs](https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md#understanding-rolling-update-of-spilo-pods) for details.

A compelling but untested solution is to add the annotations to the operator's [common values](https://github.com/defenseunicorns/zarf-package-software-factory/blob/main/kustomizations/postgres-operator/postgres-operator/common-values.yaml) in the `configKubernetes.ignored_annotations` property like this:

```
...
configKubernetes:
  ignored_annotations:
    - example-ignored-annotation
```

More information on `ignored_annotations` is [available here](https://postgres-operator.readthedocs.io/en/latest/reference/operator_parameters/#kubernetes-resources).

**Comment by RothAndrew** [comment]
Fixed by changing `configGeneral.enable_lazy_spilo_upgrade` to true in #319
