### ISSUE TITLE
Redis AOF file is corrupted if node fails

### ISSUE THREAD

**Issue by david--wright** [defenseunicorns/zarf-package-software-factory#318]
When the node Redis is on drops it leaves a half written record in the AOF file. This results in `badfile reading the append only file` 
 errors when the Redis pod restarts 

If no configuration has been done you can just delete the Redis node and the Redis PVC and they regenerate without issue but once configurations are in place in place that's not an option. 

Some possible options for fixing it can be found here:
https://redis.io/docs/manual/persistence/

This issue is handled automatically in newer versions of Redis. Alternatively Redis does provide a tool that fixes the file `redis redis-check-aof --fix appendonly.aof`

**Comment by RothAndrew** [comment]
The permanent solution here is likely to deploy redis separately in a more robust way.

https://docs.gitlab.com/charts/installation/deployment.html#redis

**Comment by RothAndrew** [comment]
Quick high level design:

* Deploy [Repo1's Redis Helm Chart](https://repo1.dso.mil/platform-one/big-bang/apps/application-utilities/redis) in multi-replica mode, ensuring Sentinal is being used
* Update GitLab configuration to use external redis and point it at the new deployment

**Comment by mikevanhemert** [comment]
Redis is being packaged / deployed on the feature branch. Next step: [configure Redis Sentinel](https://repo1.dso.mil/platform-one/big-bang/apps/application-utilities/redis) then [configure GitLab](https://docs.gitlab.com/charts/charts/globals.html#redis-sentinel-support) to use BigBang Redis

**Comment by mikevanhemert** [comment]
Redis is deploying with Sentinel in HA! Connecting GitLab will require a [secret](https://docs.gitlab.com/charts/charts/registry/index.html#redis-cache-secret). Should I tried to follow Minio's pattern with the `minio-user-credentials` secret that was added to the Big Bang Kustomization @RothAndrew ?

**Comment by RothAndrew** [comment]
> Redis is deploying with Sentinel in HA! Connecting GitLab will require a [secret](https://docs.gitlab.com/charts/charts/registry/index.html#redis-cache-secret). Should I tried to follow Minio's pattern with the `minio-user-credentials` secret that was added to the Big Bang Kustomization @RothAndrew ?

Noice!

Works for me. I think that's reasonable. Or if we wanted to generify it into just one folder/file called "secrets" I think that makes sense too. Your call.
