### ISSUE TITLE
Enable SSH for Git CLI actions

### ISSUE THREAD

**Issue by audreytoskin** [defenseunicorns/zarf-package-software-factory#340]
Currently, pushing/pulling/etc with `git` only works with GitLab over HTTPS with a personal access token. It would be convenient if we could use SSH and keys instead.

It seems port 22 isn't routed or open right now.

**Comment by RothAndrew** [comment]
Is this a "nice to have"? Or more than that? Opening up SSH access can be quite challenging. Repo1 doesn't even do it.

**Comment by david--wright** [comment]
This is a parity with di2e feature that alot of our users used. How critical it is we will have to ask around.

**Comment by RothAndrew** [comment]
Closing for now as wontfix. I'm perceiving the value it brings being not worth the engineering effort. Happy to reopen if you guys feel like this is a must-have.
