### ISSUE TITLE
Ability to provide RWX PVCs on non-cloud envs

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf-package-software-factory#401]
As a user of DI2-ME that uses the package in an edge/classified/airgapped environment, I want the ability to use Read-Write-Many (RWX) Persistent Volume Claims (PVCs) so that the services that need RWX are able to utilize them.

Acceptance Criteria:
1. I'm able to create an RWX PVC when using DI2-ME on a single-node K3s cluster provisioned by Zarf with no other dependencies (like cloud services)
2. I'm able to `<insert method of ensuring that the RWX PVC actually works>` (attach 2 pods to the same PVC?)
3. The functionality is tested in the CI pipeline

Notes:
- The primary driving motivation for wanting this is the fact that Jira and Confluence need RWX PVCs for their "Shared Home" volume. Without it both Jira and Confluence will lose data on any pod restart.
- This story is a "must have" if we are to continue saying DI2-ME can be run in an air gap where there are no cloud services to lean on. Otherwise we will need to add a caveat that Jira and Confluence won't work without a lot of additional work (or usage of cloud services)
- This story has the potential to get quite hairy, if we end up needing to go to tools like Longhorn or Rook/Ceph or OpenEBS or Gluster 😱 or something equally heavyweight and horrifying.
- We'll likely want an ADR for documenting what we decide to use.
- Doing this on a single-node K3s is just the first step. Follow-on stories will likely involve multi-node clusters, most likely using RKE2
- This is a big unsolved problem in a lot of gov orgs. It would be huge benefit if we were able to pull it off in an easily consumable way.

**Comment by RothAndrew** [comment]
@brianrexrode @kirankt grooming feedback pls

@jeff-mccoy any thoughts from that big brain of yours?

**Comment by RothAndrew** [comment]
My gut feeling right now is that Longhorn is the best way to do, but this definitely deserves some thought

**Comment by runyontr** [comment]
From what I recall in looking at this from Jiras side, you can use RWOnce and lose high availability and 0 downtime restarts by forcing the replicas to be 1 and the strategy to be Recreate.

It's a tradeoff for sure, but this might be an easier pill to swallow than a RWX storage provider

**Comment by RothAndrew** [comment]
@runyontr The customer I was working with at the time when we were setting up Jira mentioned they still lost data even when we did that. I'd need to look into it again to be more confident, but I'm not sure even that gets us there.

Got any more info I can look at on what you're saying? You're right, in the short term it's a fine solution to lose HA and zero downtime if it means avoiding data loss

**Comment by RothAndrew** [comment]
We may not have done the recreate strategy, just the replicas. Definitely something to look at. Thanks!

**Comment by brianrexrode** [comment]
Design discussion.
- Add longhorn as a separate zarf package to the DI2-ME repo with the intention of installing it after the flux package and before the DI2-ME package.
- Use a flux helmRelease object backed by the upstream open source longhorn [helmChart](https://github.com/longhorn/longhorn/tree/master/chart).
- Use upstream docker image, for now.
- Change all existing storageClass parameters to the longhorn storageClass.

**Comment by matthew-l-weber** [comment]
I've been considering using longhorn as the primary storage class for the whole air-gapped cluster.  Such that as part of zarf init, it could be deployed before any storage claims and then inherited through the rest of deployments?

**Comment by matthew-l-weber** [comment]
> Design discussion.
> 
> * Add longhorn as a separate zarf package to the DI2-ME repo with the intention of installing it after the flux package and before the DI2-ME package.

I've been considering using longhorn as the primary storage class for the whole air-gapped cluster.  So as part of zarf init, would it need to be deployed before any storage claims (registry, gitea) and then inherited through the rest of deployments?

**Comment by corang** [comment]
Jira and Confluence have full persistence by default as of now by using a RWO volume for their shared home volumes. This needs to be documented and have an ADR written explaining it and how to configure to change to HA / RWX
