### ISSUE TITLE
Move E2E test from PRs to main

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf-package-software-factory#442]
Current process:

* E2E tests run as part of PRs. If they pass, the PR can be merged into main
* PRs are required to be up to date with the latest changes in main before being merged
* Because of this, the tests are not run again in main. There would be no point, since they would always run against the same commit as before

Advantages to current process:

* Broken code is almost never merged into main since there's a quality gate that happens before the merge

Drawbacks to current process:

* PRs take a long time to merge because the E2E tests take a long time to run (they are up to ~55 minutes). Even 1-line changes or changes to things that don't affect the codebase (like documentation) take a long time
* If `main` changes before the PR gets merged the tests need to be run again after the new changes are integrated into the feature branch

Proposed new process:

* Only run tests in PRs that take less than 5 minutes. Anything longer than that is not required and not run automatically until the change hits `main`
* Run all tests on each new commit to `main`
* Immediately prioritize broken code that has made it into `main` (pipeline red to pipeline green) over all other work.
* Longer tests can still be run in a PR if desired by using chatops comments (`/test all`). All tests still run again once the change hits main, even if it isn't technically needed. We may want to keep doing this for any PRs that external contributors create since broken code will most likely end up on our plates to fix rather than the 3rd party contributor's.

Advantages to new process:

* Quality gates on PRs are now much shorter
* Process is much closer to Trunk-Based Development without losing the goodness of using PRs in an open source product. Feature branch TTL is likely significantly reduced.

Disadvantages to new process:

* `main` won't be as "clean", but we can mitigate by adding a note to the docs that `main` is bleeding edge and never guaranteed to be of the same stabiliy/quality as a published release

**Comment by RothAndrew** [comment]
@brianrexrode @kirankt PTAL

**Comment by RothAndrew** [comment]
@bdfinst interested to hear any thoughts you have on this

**Comment by brianrexrode** [comment]
I agree with your purposed changes and think the key here is advertising that `main` is not always considered `released`. E2E testing must be completed on `main` prior to creating a new release.

Users of this repo should always be using released tags for production deployments.

**Comment by RothAndrew** [comment]
We'll have to balance users' ability to upgrade between releases with doing frequent releases. If we do new releases very frequently it will make that incredibly difficult if we are only doing automated testing of the upgrade path between version N and version N+1

**Comment by RothAndrew** [comment]
Right now the idea of doing a release every 2 weeks (to match Big Bang's cadence since that's what we'll most likely be changing the most) sounds like a good path to me
