### ISSUE TITLE
zarf deploy complete (but not complete) on rke2 w/ longhorn storage

### ISSUE THREAD

**Issue by matthew-l-weber** [defenseunicorns/zarf-package-software-factory#448]
**Baselines**
Ubuntu 20.04
Kubernetes - v1.24.7+rke2r1
Longhorn stable that matches v1.24
zarf [v0.21.3-30-gda29f99]
zarf-package-software-factory [5847243dfd9f49cfa95cd39a07912a73bea18bbc ]

**Deploy**
zarf init --components git-server --confirm
zarf package deploy zarf-package-flux-amd64.tar.zst --confirm
zarf package deploy zarf-package-software-factory-amd64.tar.zst --confirm

The result is good up to the ` zarf-package-software-factory-amd64.tar.zst` where I see no new namespaces or items deployed, however, the zarf output is as follows.
![image](https://user-images.githubusercontent.com/1114905/201343890-19f49c45-f5c3-4600-99d8-289c406fb988.png)

Do you guys have a support/chat I can jump on to discuss?

**Comment by RothAndrew** [comment]
Yep. We are in the K8s slack in the #zarf channel

**Comment by RothAndrew** [comment]
What happens when you deploy a much simpler package like the game example?

**Comment by matthew-l-weber** [comment]
> What happens when you deploy a much simpler package like the game example?

Good point, I'll try that

**Comment by matthew-l-weber** [comment]
https://kubernetes.slack.com/archives/C03B6BJAUJ3/p1668181840370379

**Comment by RothAndrew** [comment]
![image](https://user-images.githubusercontent.com/16000938/201399343-bcd5214b-1c44-4574-a90c-7e2b0d87739f.jpeg)
