### ISSUE TITLE
Check if user is sudo

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf-package-software-factory#520]
As a deployer of DI2-ME, I want better clarity around what I am or am not able to do if I am not using sudo.

**Context:**

In any component that requires sudo, which currently is:

* `flux-cli` component (always)
* all other components (only if k3s was used which requires sudo to deploy and sudo to connect to)

We don't do any warning or anything, we just fail if we try to do something that requires sudo when it isn't being used.

**Suggested Fix:**

We can do a simple check for sudo at the beginning of the deployment and fail if not sudo.

**Comment by RothAndrew** [comment]
cc @corang thoughts?

**Comment by corang** [comment]
I'm thinking a better way to go about this is to not require sudo for a zarf deploy. My thought is to parse out a user owned folder from $PATH and put the executable there, it requires some extra bash but I think is a more reasonable solution. Example:
```
#!/bin/bash

# Store a list of folders in $PATH
PATH_FOLDERS=$(echo $PATH | sed 's/:/\n/g')

# Store the owners of each folder in PATH_FOLDERS
PATH_OWNERS=$(echo "$PATH_FOLDERS" | xargs -I {} stat -c "%U" {})

# Get the first occurence of the current use in PATH_OWNERS and store it's line number
FIRST_OWNED_INDEX=$(echo "$PATH_OWNERS" | grep -n "$USER" | head -n 1 | cut -d: -f1)

# Get the folder at the line number FIRST_OWNED_INDEX in PATH_FOLDERS
FIRST_OWNED_PATH_FOLDER=$(echo "$PATH_FOLDERS" | sed -n "$FIRST_OWNED_INDEX"p)

echo "$FIRST_OWNED_PATH_FOLDER"
```

**Comment by corang** [comment]
I didn't know sudo was required if k3s was used, you're referring to k3s via the zarf init package right?

**Comment by corang** [comment]
I guess in that case the check is best, I'm trying to think about how to only check for sudo if it's actually needed when deploying

**Comment by corang** [comment]
I think failing the `zarf deploy` if the k3s component was used is fine and we should just add the check to the `flux-cli` component via bash. I'm assuming that zarf failing the way it does when run with the k3s component and without sudo is intentional and if it isn't it should be fixed on the zarf side because it isn't reasonable for us to implement a check thats able to see if k3s was deployed or not (I can think of a way or two but it would be very ugly and pollute the package)

**Comment by corang** [comment]
Implement above example specifically into the optional-tools component to make it fail prettier when not run as root
