### ISSUE TITLE
Disable Istio VirtualServices for all services other than GitLab, Jenkins, Jira, Confluence, and Nexus

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf-package-software-factory#68]
We're set up right now to expose VirtualServices for other services like Grafana, Kibana, etc. Until we can get SSO configured for them we need to just disable the VirtualServices so that only cluster users/sysadmins can use them via `kubectl port-forward`

**Comment by blancharda** [comment]
As an alternative to disabling the virtual services, what if we only add the "allowed" service hostnames to the public gateway?

The "disallowed" virtual services would still exist, but they won't bind to any istio gateways (i.e. no traffic will route to them).

**Comment by RothAndrew** [comment]
works for me

**Comment by blancharda** [comment]
WIP PR: #78
