### ISSUE TITLE
Upgrade Zarf version to latest

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf-package-software-factory#71]
Now that 0.18.0 is out we should use it

**Comment by jeff-mccoy** [comment]
Yeah I am using it right now, sbom takes a hot minute on this package and might be worth doing a pr for "skip-sbom" or something for zarf.

**Comment by jeff-mccoy** [comment]
[0.18.1](https://github.com/defenseunicorns/zarf/releases/tag/v0.18.1) is out now

**Comment by RothAndrew** [comment]
This is fixed, we're on 0.19.5 now and Renovate is now set up to submit PRs for zarf upgrades automatically.
